/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppLoader: typeof import('./components/layout/AppLoader.vue')['default']
    AutoForm: typeof import('./components/AutoForm.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
